<?php

declare(strict_types=1);

namespace Normalizzatore\Frazione;

enum FrazioneResolutionDiagnostic: string
{
    case NO_DIRECTORY_VERIFIED_MUNICIPALITY = 'NO_DIRECTORY_VERIFIED_MUNICIPALITY';
    case UNKNOWN_TYPE = 'UNKNOWN_TYPE';
    case MULTIPLE_VERIFIED_MUNICIPALITIES = 'MULTIPLE_VERIFIED_MUNICIPALITIES';
    case SOURCE_PROVINCE_NOT_DISAMBIGUATING = 'SOURCE_PROVINCE_NOT_DISAMBIGUATING';
    case CATALOG_CAP_CONFLICT = 'CATALOG_CAP_CONFLICT';
    case INCOMPLETE_TERRITORIAL_ALTERNATIVE = 'INCOMPLETE_TERRITORIAL_ALTERNATIVE';
    case SOURCE_PROVINCE_CONFLICT = 'SOURCE_PROVINCE_CONFLICT';
}
