<?php

declare(strict_types=1);

namespace Normalizzatore\Frazione;

enum FuzzyFrazioneResolutionDiagnostic: string
{
    case NO_NOMINAL_CANDIDATE = 'NO_NOMINAL_CANDIDATE';
    case MULTIPLE_NOMINAL_CANDIDATES = 'MULTIPLE_NOMINAL_CANDIDATES';
    case NO_PROVINCIAL_CANDIDATE = 'NO_PROVINCIAL_CANDIDATE';
    case SOURCE_PROVINCE_MISSING_OR_INVALID = 'SOURCE_PROVINCE_MISSING_OR_INVALID';
    case TERRITORY_UNVERIFIED = 'TERRITORY_UNVERIFIED';
    case INCOMPLETE_TERRITORIAL_ALTERNATIVE = 'INCOMPLETE_TERRITORIAL_ALTERNATIVE';
    case MULTIPLE_TERRITORIAL_ASSOCIATIONS = 'MULTIPLE_TERRITORIAL_ASSOCIATIONS';
    case TARGET_IS_EXACT_MUNICIPALITY = 'TARGET_IS_EXACT_MUNICIPALITY';
    case STREET_NOT_VERIFIED = 'STREET_NOT_VERIFIED';
    case CIVIC_NOT_COMPATIBLE = 'CIVIC_NOT_COMPATIBLE';
    case CIVIC_INDETERMINATE = 'CIVIC_INDETERMINATE';
    case ADDRESS_NOT_RESOLVED = 'ADDRESS_NOT_RESOLVED';
    case EXACT_CITY_PRECEDENCE = 'EXACT_CITY_PRECEDENCE';
    case EXACT_FRACTION_PRECEDENCE = 'EXACT_FRACTION_PRECEDENCE';
    case FUZZY_CITY_PRECEDENCE = 'FUZZY_CITY_PRECEDENCE';
    case FUZZY_CITY_AMBIGUOUS = 'FUZZY_CITY_AMBIGUOUS';
}
