<?php

declare(strict_types=1);

namespace Normalizzatore\Resolution;

enum AddressGeographicEvidenceKind: string
{
    case PROVINCE_COMPLETION = 'PROVINCE_COMPLETION';
    case PROVINCE_CORRECTION = 'PROVINCE_CORRECTION';
    case FUZZY_CITY_CORRECTION = 'FUZZY_CITY_CORRECTION';
    case TERRITORIAL_STREET_RECOVERY = 'TERRITORIAL_STREET_RECOVERY';
    case FRAZIONE_TO_COMUNE = 'FRAZIONE_TO_COMUNE';
    case FUZZY_FRAZIONE_TO_COMUNE = 'FUZZY_FRAZIONE_TO_COMUNE';
}
